version:  '3.7'

services:
  notify:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - './config/dev.yaml:/app/config.yaml'
    ports:
      - '${NOTIFY_PORT}:80'
    depends_on:
      - kafka

  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - '${KAFKA_PORT}:9092'
    volumes:
      - '.build/kafka/data:/bitnami'
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=${KAFKA_CFG_NODE_ID}
      - KAFKA_CFG_PROCESS_ROLES=${KAFKA_CFG_PROCESS_ROLES}
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
      # Listeners
      - KAFKA_CFG_LISTENERS=${KAFKA_CFG_LISTENERS}
      - KAFKA_CFG_ADVERTISED_LISTENERS=${KAFKA_CFG_ADVERTISED_LISTENERS}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=${KAFKA_CFG_INTER_BROKER_LISTENER_NAME}

